### ISSUE TITLE
Terminates and Rollback on Route 53 setup

### ISSUE THREAD

**Issue by summithr** [awslabs/aws-refarch-wordpress#15]
Hello,

I've tried to utilise this stack twice without success. As soon as it tries to set up the Route 53 section it fails, terminates and rolls back. I'm trying to set it up in ap-southeast-2 using the launch button. Whilst I'm no AWS expert I can't see what I might be doing wrong.

Also, I note whilst ap-southeast-2 is listed as supported in the description here, it is not listed in the CloudFormation stack description, only the other regions are. Any advice is appreciated.

Nathan
[Stack Detail.pdf](https://github.com/awslabs/aws-refarch-wordpress/files/1565778/Stack.Detail.pdf)

**Comment by michael-newman** [comment]
Nathan,

I had a Route53 rollback due to not creating a Hosted Zone  prior to running the template as the template creates the record set, not the Hosted Zone itself--in my case, I was just trying to test the CloudFormation template on test.mysite.com and realized the template rolls back if the test.mysite.com Hosted Zone is not created ahead of time  and fails if run just on mysite.com as it does not create my desired test.mysite.com Hosted Zone.

If you are trying to just run this on mysite.com, know the template desires to create an A-Record of www.mysite.com... so, if this record already exists in Route53, it can't create another one and I would expect the template to fail/rollback.

Just sharing a couple of my experiences for your consideration...

Regards, Mike

**Comment by darrylsosborne** [comment]
Nathan,

Mike is right.  Create the hosted zone first using Route 53 then include the domain name as the WPDomain parameter. 

It is fully supported in ap-southeast-2.

Let us know if this resolves your issue.

Darryl

**Comment by summithr** [comment]
Hello Mike & Darryl,

Thanks for the prompt response, much appreciated. 

Yes, I was going to try setting up the record framework and running the script though wasn't such how much needed to be entered without interrupting the script. I may use white label nameservers in the future so I'll consider options in terms of when I set the Route 53 records up. Thanks again for your assistance.

Regards

Nathan
